In [1]:
import numpy as np

In [12]:
A=np.matrix([[1,2,3],[2,7,4]])

In [6]:
B=np.matrix([[1 ,-1],[0 ,1]])

In [8]:
C=np.matrix([[5,-1],[9,1],[6,0]])

In [9]:
D=np.matrix([[3,-2,-1],[1,2,3]])

In [14]:
np.add(A,C)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [15]:
np.subtract(A,C.transpose())

matrix([[-4, -7, -3],
        [ 3,  6,  4]])

In [16]:
np.add(C.transpose(),3*D)

matrix([[14,  3,  3],
        [ 2,  7,  9]])

In [17]:
B*A

matrix([[-1, -5, -1],
        [ 2,  7,  4]])

In [22]:
np.dot(B,A.transpose())

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

matrix([[ 5, -5],
        [ 4,  5]])

In [26]:
B*B*B*B

matrix([[ 1, -4],
        [ 0,  1]])